# Errors

This page acts as a reference for the error codes returned by IDKit, the Developer Portal API, and the Wallet Bridge.

## IDKit

These error codes are returned in the `onError` callback.

<table>
	<thead>
		<tr>
			<th>Code</th>
			<th>Description</th>
			<th>How to fix?</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>`failed_by_host_app`</td>
			<td>An error was thrown in the `handleVerify` callback.</td>
			<td>
				Assess the error thrown in your `handleVerify` callback and resolve the issue.
			</td>
		</tr>
		<tr>
			<td>`connection_failed`</td>
			<td>Could not establish a connection to World App.</td>
			<td>
				Ask the user to check their internet connection on both devices running your application and World App.
				Additionally, make sure the user has the latest version of World App.
			</td>
		</tr>
		<tr>
			<td>`verification_rejected`</td>
			<td>User rejected the World ID request in World App.</td>
			<td>If this was a mistake, ask the user to go through the flow again.</td>
		</tr>
		<tr>
			<td>`max_verifications_reached`</td>
			<td>This person has already verified for this particular action the maximum number of times allowed.</td>
			<td>Nothing to do. User cannot verify for this action again.</td>
		</tr>
		<tr>
			<td>`credential_unavailable`</td>
			<td>This user does not have the requested credential.</td>
			<td>The user must verify at the Orb or verify their unique device in World App to receive the credential required.</td>
		</tr>
		<tr>
			<td>`malformed_request`</td>
			<td>The request payload couldn't be decrypted or did not conform to the standard.</td>
			<td>Ensure IDKit is configured properly and all parameters are valid. See [above](#id-kit-react) for configuration details.</td>
		</tr>
		<tr>
			<td>`invalid_network`</td>
			<td>The application is configured for a different environment than the verifying user's client.</td>
			<td>Ensure you use the [Worldcoin Simulator](https://simulator.worldcoin.org) for Staging applications and World App for Production applications.</td>
		</tr>
		<tr>
			<td>`inclusion_proof_failed`</td>
			<td>The sequencer returned an unexpected error when retrieving the inclusion proof.</td>
			<td>Ask the user to try again. This may be due to a temporary network issue, or a bug with World App or the Signup Sequencer.</td>
		</tr>
		<tr>
			<td>`inclusion_proof_pending`</td>
			<td>The user might have the requested credential, but it is not available on-chain yet. It might be available for API verification.</td>
			<td>Ask the user to verify again in approximately one hour.</td>
		</tr>
		<tr>
			<td>`unexpected_response`</td>
			<td>There was a problem with the response obtained from the WLD app.</td>
			<td>
				Check the JS console for further details, though in most cases these will require contacting us to
				report the bug.
			</td>
		</tr>
		<tr>
			<td>`generic_error`</td>
			<td>An unhandled exception occurred.</td>
			<td>
				Check the JS console for further details, though in most cases these will require contacting us to
				report the bug.
			</td>
		</tr>
	</tbody>
</table>

## Developer Portal API

These error codes are returned in the `error` property of the response body.

<table>
	<thead>
		<tr>
			<th>Code</th>
			<th>Description</th>
			<th>How to fix?</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>`required`</td>
			<td>The attribute named in the `attribute` property is required, but was not included in the request.</td>
			<td>Provide the required attribute in your API request.</td>
		</tr>
		<tr>
			<td>`invalid_format`</td>
			<td>The attribute named in the `attribute` property was provided, but was in an unexpected format.</td>
			<td>See the error message for the proper format.</td>
		</tr>
		<tr>
			<td>`unauthenticated`</td>
			<td>The credentials (if provided) were invalid.</td>
			<td>Provide the required credentials in your API request and ensure they are correct.</td>
		</tr>
		<tr>
			<td>`permission_denied`</td>
			<td>The credentials provided were valid, but you do not have the required permissions.</td>
			<td>Contact your Developer Portal team's owner to be granted permissions, or the Worldcoin team if you are unable to resolve the issue.</td>
		</tr>
		<tr>
			<td>`max_verifications_reached`</td>
			<td>This person has already verified for this particular action the maximum number of times allowed.</td>
			<td>Nothing to do. User cannot verify for this action again.</td>
		</tr>
		<tr>
			<td>`invalid_proof`</td>
			<td>The provided proof is invalid and it cannot be verified.</td>
			<td>Ensure your `app_id`, `action`, `signal`, and `credential_type` are unchanged between the proof request and proof verification.</td>
		</tr>
		<tr>
			<td>`invalid_merkle_root`</td>
			<td>The merkle root provided is not recognized.</td>
			<td>Ask the user to generate a new proof, the existing proof may be stale.</td>
		</tr>
		<tr>
			<td>`invalid_network`</td>
			<td>The application is configured for a different environment than the verifying user's client.</td>
			<td>Ensure you use the [Worldcoin Simulator](https://simulator.worldcoin.org) for Staging applications and World App for Production applications.</td>
		</tr>
		<tr>
			<td>`invalid_engine`</td>
			<td>The application is configured for on-chain verification and cannot be verified via API.</td>
			<td>Either verify the proof on-chain or create a new application configured for Cloud verifications.</td>
		</tr>
		<tr>
			<td>`metadata_failed`</td>
			<td>Unable to load metadata for the app from the Developer Portal.</td>
			<td>Ensure your `app_id` is configured correctly in IDKit and exactly matches the `app_id` from the Developer Portal.</td>
		</tr>
		<tr>
			<td>`action_inactive`</td>
			<td>The requested action is disabled in the Developer Portal.</td>
			<td>Enable the action or create a new action.</td>
		</tr>
		<tr>
			<td>`verification_error`</td>
			<td>The Developer Portal faced an internal error verifying the proof.</td>
			<td>Contact the Worldcoin team.</td>
		</tr>
		<tr>
			<td>`internal_error`</td>
			<td>The Developer Portal faced an internal error verifying the proof.</td>
			<td>Contact the Worldcoin team.</td>
		</tr>
		<tr>
			<td>`unexpected_response`</td>
			<td>There was a problem with the response obtained from the WLD app.</td>
			<td>
				Check the JS console for further details, though in most cases these will require contacting us to
				report the bug.
			</td>
		</tr>
		<tr>
			<td>`generic_error`</td>
			<td>An unhandled exception occurred.</td>
			<td>
				Check the JS console for further details, though in most cases these will require contacting us to
				report the bug.
			</td>
		</tr>
	</tbody>
</table>

## Wallet Bridge

These error codes are returned by the Wallet Bridge to IDKit in the proof response.

<table>
	<thead>
		<tr>
			<th>Code</th>
			<th>Description</th>
			<th>How to fix?</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>`verification_rejected`</td>
			<td>User rejected the World ID request in World App.</td>
			<td>If this was a mistake, ask the user to go through the flow again.</td>
		</tr>
		<tr>
			<td>`max_verifications_reached`</td>
			<td>This person has already verified for this particular action the maximum number of times allowed.</td>
			<td>Nothing to do. User cannot verify for this action again.</td>
		</tr>
		<tr>
			<td>`credential_unavailable`</td>
			<td>This user does not have the requested credential.</td>
			<td>The user must verify at the Orb or verify their unique device in World App to receive the credential required.</td>
		</tr>
		<tr>
			<td>`malformed_request`</td>
			<td>The request payload couldn't be decrypted or did not conform to the standard.</td>
			<td>Ensure IDKit is configured properly and all parameters are valid. See [above](#id-kit-react) for configuration details.</td>
		</tr>
		<tr>
			<td>`inclusion_proof_failed`</td>
			<td>The sequencer returned an unexpected error when retrieving the inclusion proof.</td>
			<td>Ask the user to try again. This may be due to a temporary network issue, or a bug with World App or the Signup Sequencer.</td>
		</tr>
		<tr>
			<td>`inclusion_proof_pending`</td>
			<td>The user might have the requested credential, but it is not available on-chain yet. It might be available for API verification.</td>
			<td>Ask the user to verify again in approximately one hour.</td>
		</tr>
		<tr>
			<td>`invalid_network`</td>
			<td>The application is configured for a different environment than the verifying user's client.</td>
			<td>Ensure you use the [Worldcoin Simulator](https://simulator.worldcoin.org) for Staging applications and World App for Production applications.</td>
		</tr>
		<tr>
			<td>`metadata_failed`</td>
			<td>Unable to load metadata for the app from the Developer Portal.</td>
			<td>Ensure your `app_id` is configured correctly in IDKit and exactly matches the `app_id` from the Developer Portal.</td>
		</tr>
		<tr>
			<td>`generic_error`</td>
			<td>An unhandled exception occurred.</td>
			<td>
				Check the JS console for further details, though in most cases these will require contacting us to
				report the bug.
			</td>
		</tr>
	</tbody>
</table>